"""Prompt-injection defenses at ingress.

Two independent layers, because neither is sufficient alone:

* Heuristics here, which are deterministic, free, and run before any model sees
  the question — so a hijack attempt costs nothing and cannot influence the
  classifier that would otherwise be asked to judge it.
* The classifier's `safety_flag`, which catches phrasings no regex anticipated.

A blocked question does not enter the pipeline at all. That is the point: a
refusal generated by the same model the attacker is addressing is a weaker
control than never running the pipeline.

Retrieved documents are handled separately, by `app.guardrails.spotlight` —
instructions found inside evidence are data to be summarized, never directives.
"""

import logging
import re
from dataclasses import dataclass, field
from typing import Any

from app.guardrails.spotlight import neutralize

logger = logging.getLogger(__name__)

# Score at or above which the question is refused without running the pipeline.
# Set so that any single high-signal phrase blocks on its own, while a lone weak
# signal (a stray base64 blob, the word "password") does not.
BLOCK_THRESHOLD = 0.5

# (name, pattern, weight). Weights are additive and capped at 1.0. They encode
# how unambiguous each phrasing is: "print your system prompt" has no innocent
# reading, "pretend you are" often does.
PATTERNS: list[tuple[str, re.Pattern[str], float]] = [
    (
        "instruction_override",
        re.compile(
            r"\b(ignore|disregard|forget|discard|override)\b[^.\n]{0,40}?"
            r"\b(instruction|instructions|prompt|prompts|rule|rules|directive|"
            r"directives|guideline|guidelines|context)\b",
            re.I,
        ),
        0.7,
    ),
    (
        "prompt_disclosure",
        re.compile(
            r"\b(reveal|show|print|output|repeat|display|dump|disclose|recite)\b"
            r"[^.\n]{0,30}?\b(system\s+)?(prompt|instructions|rules|configuration)\b",
            re.I,
        ),
        0.8,
    ),
    (
        "prompt_interrogation",
        re.compile(
            r"\bwhat\s+(are|were|is)\s+(your|the)\b[^.\n]{0,30}?"
            r"\b(system\s+)?(prompt|instructions)\b",
            re.I,
        ),
        0.6,
    ),
    (
        "role_hijack",
        re.compile(
            r"\b(you\s+are\s+now|from\s+now\s+on\s+you|act\s+as\s+(?:an?\s+)?"
            r"(?:unrestricted|jailbroken|developer\s+mode)|enable\s+developer\s+mode"
            r"|\bDAN\b|jailbreak)\b",
            re.I,
        ),
        0.6,
    ),
    (
        "safety_bypass",
        re.compile(
            r"\b(bypass|disable|turn\s+off|switch\s+off|circumvent|remove)\b"
            r"[^.\n]{0,30}?\b(safety|guardrail|guardrails|filter|filters|"
            r"restriction|restrictions|policy|policies)\b",
            re.I,
        ),
        0.7,
    ),
    (
        "exfiltration",
        re.compile(
            r"\b(send|post|upload|exfiltrate|forward|email|transmit|leak)\b"
            r"[^.\n]{0,40}?\b(to\s+)?(https?://|www\.|[\w.+-]+@[\w-]+\.\w+)",
            re.I,
        ),
        0.8,
    ),
    (
        "credential_probe",
        re.compile(
            r"\b(api[\s_-]?key|secret\s+key|access\s+token|password|credential"
            r"|credentials|\.env\b|environment\s+variable)\b",
            re.I,
        ),
        0.4,
    ),
    (
        "corpus_exfiltration",
        re.compile(
            r"\b(list|dump|export|reproduce|output)\b[^.\n]{0,30}?"
            r"\b(all|every|entire|whole)\b[^.\n]{0,30}?"
            r"\b(document|documents|corpus|chunk|chunks|evidence|record|records)\b",
            re.I,
        ),
        0.6,
    ),
    (
        "delimiter_forgery",
        re.compile(
            r"(<\|?(?:im_start|im_end|endoftext|system)\|?>|^\s*(?:system|assistant)\s*:)",
            re.I | re.M,
        ),
        0.5,
    ),
    (
        "encoded_payload",
        # A long unbroken base64-ish run is not something a research question
        # contains. Weak on its own; damning next to anything else.
        re.compile(r"[A-Za-z0-9+/]{60,}={0,2}"),
        0.3,
    ),
]


@dataclass
class InjectionVerdict:
    """Result of screening one piece of user input."""

    blocked: bool
    risk: float
    matched_patterns: list[str] = field(default_factory=list)
    reason: str = ""
    safety_flag: bool = False

    def to_dict(self) -> dict[str, Any]:
        """Serialize for graph state and traces."""
        return {
            "blocked": self.blocked,
            "risk": self.risk,
            "matched_patterns": self.matched_patterns,
            "reason": self.reason,
            "safety_flag": self.safety_flag,
        }


def scan_input(text: str, safety_flag: bool | None = None) -> InjectionVerdict:
    """Score user input for injection/jailbreak patterns.

    Args:
        text: the raw user question.
        safety_flag: the classifier's own judgement, when it has already run.
            `True` blocks regardless of what the heuristics scored — the model
            catches phrasings the patterns above do not anticipate.

    Returns:
        An `InjectionVerdict`; `blocked` is what the graph acts on.
    """
    matched: list[str] = []
    risk = 0.0

    for name, pattern, weight in PATTERNS:
        if pattern.search(text or ""):
            matched.append(name)
            risk += weight

    risk = round(min(1.0, risk), 3)
    flagged = bool(safety_flag)
    blocked = risk >= BLOCK_THRESHOLD or flagged

    if blocked:
        reasons = []
        if matched:
            reasons.append(f"matched {', '.join(matched)} (risk {risk})")
        if flagged:
            reasons.append("classifier safety_flag set")
        reason = "; ".join(reasons)
        # Log the verdict, not the payload — the question may itself be an
        # exfiltration attempt and logs are a downstream sink.
        logger.warning("injection screen BLOCKED: %s", reason)
    else:
        reason = f"no injection signal above threshold (risk {risk})"

    return InjectionVerdict(
        blocked=blocked,
        risk=risk,
        matched_patterns=matched,
        reason=reason,
        safety_flag=flagged,
    )


def build_refusal(verdict: InjectionVerdict) -> dict[str, Any]:
    """Build a safe refusal in the same shape as a synthesized answer.

    Deliberately says nothing about which patterns fired and echoes none of the
    question back — both would be free feedback for tuning the next attempt.
    """
    return {
        "recommendation": (
            "This request was blocked before any research ran. It contains "
            "instructions that attempt to change how this system behaves or to "
            "extract its configuration, rather than asking a research question. "
            "Please rephrase as a question about the transformation programme."
        ),
        "key_factors": [],
        "conflicts": [],
        "confidence": 0.0,
        "limitations": [
            "No retrieval or synthesis was performed for this request.",
        ],
        "citations": [],
        "blocked": True,
        "block_reason": "prompt_injection_screen",
        "risk": verdict.risk,
    }


def sanitize_evidence(content: str) -> str:
    """Neutralize instruction-like structure inside retrieved content.

    Thin wrapper over `spotlight.neutralize`, kept here so callers reasoning
    about untrusted input have one obvious import. Spotlighting applies this to
    every evidence item automatically; this is for anything that reaches a
    prompt outside that path.
    """
    return neutralize(content)
